//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"

	consolev1 "github.com/IBM-Blockchain/fabric-operator/api/console/v1"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAConnectionProfile) DeepCopyInto(out *CAConnectionProfile) {
	*out = *in
	out.Endpoints = in.Endpoints
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ConnectionProfileTLS)
		**out = **in
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSCA != nil {
		in, out := &in.TLSCA, &out.TLSCA
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAConnectionProfile.
func (in *CAConnectionProfile) DeepCopy() *CAConnectionProfile {
	if in == nil {
		return nil
	}
	out := new(CAConnectionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CACustomNames) DeepCopyInto(out *CACustomNames) {
	*out = *in
	out.PVC = in.PVC
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CACustomNames.
func (in *CACustomNames) DeepCopy() *CACustomNames {
	if in == nil {
		return nil
	}
	out := new(CACustomNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAResources) DeepCopyInto(out *CAResources) {
	*out = *in
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollJob != nil {
		in, out := &in.EnrollJob, &out.EnrollJob
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.HSMDaemon != nil {
		in, out := &in.HSMDaemon, &out.HSMDaemon
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAResources.
func (in *CAResources) DeepCopy() *CAResources {
	if in == nil {
		return nil
	}
	out := new(CAResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAStorages) DeepCopyInto(out *CAStorages) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(StorageSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAStorages.
func (in *CAStorages) DeepCopy() *CAStorages {
	if in == nil {
		return nil
	}
	out := new(CAStorages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRStatus) DeepCopyInto(out *CRStatus) {
	*out = *in
	out.Versions = in.Versions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRStatus.
func (in *CRStatus) DeepCopy() *CRStatus {
	if in == nil {
		return nil
	}
	out := new(CRStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSR) DeepCopyInto(out *CSR) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSR.
func (in *CSR) DeepCopy() *CSR {
	if in == nil {
		return nil
	}
	out := new(CSR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOverride) DeepCopyInto(out *ConfigOverride) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(json.RawMessage)
		if **in != nil {
			in, out := *in, *out
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
	}
	if in.TLSCA != nil {
		in, out := &in.TLSCA, &out.TLSCA
		*out = new(json.RawMessage)
		if **in != nil {
			in, out := *in, *out
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
	}
	if in.MaxNameLength != nil {
		in, out := &in.MaxNameLength, &out.MaxNameLength
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOverride.
func (in *ConfigOverride) DeepCopy() *ConfigOverride {
	if in == nil {
		return nil
	}
	out := new(ConfigOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleImages) DeepCopyInto(out *ConsoleImages) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleImages.
func (in *ConsoleImages) DeepCopy() *ConsoleImages {
	if in == nil {
		return nil
	}
	out := new(ConsoleImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOverrides) DeepCopyInto(out *ConsoleOverrides) {
	*out = *in
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(json.RawMessage)
		if **in != nil {
			in, out := *in, *out
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
	}
	if in.Deployer != nil {
		in, out := &in.Deployer, &out.Deployer
		*out = new(json.RawMessage)
		if **in != nil {
			in, out := *in, *out
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
	}
	if in.MaxNameLength != nil {
		in, out := &in.MaxNameLength, &out.MaxNameLength
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOverrides.
func (in *ConsoleOverrides) DeepCopy() *ConsoleOverrides {
	if in == nil {
		return nil
	}
	out := new(ConsoleOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOverridesConsole) DeepCopyInto(out *ConsoleOverridesConsole) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOverridesConsole.
func (in *ConsoleOverridesConsole) DeepCopy() *ConsoleOverridesConsole {
	if in == nil {
		return nil
	}
	out := new(ConsoleOverridesConsole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOverridesDeployer) DeepCopyInto(out *ConsoleOverridesDeployer) {
	*out = *in
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(DeployerTimeouts)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOverridesDeployer.
func (in *ConsoleOverridesDeployer) DeepCopy() *ConsoleOverridesDeployer {
	if in == nil {
		return nil
	}
	out := new(ConsoleOverridesDeployer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleResources) DeepCopyInto(out *ConsoleResources) {
	*out = *in
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CouchDB != nil {
		in, out := &in.CouchDB, &out.CouchDB
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployer != nil {
		in, out := &in.Deployer, &out.Deployer
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Configtxlator != nil {
		in, out := &in.Configtxlator, &out.Configtxlator
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleResources.
func (in *ConsoleResources) DeepCopy() *ConsoleResources {
	if in == nil {
		return nil
	}
	out := new(ConsoleResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleStorage) DeepCopyInto(out *ConsoleStorage) {
	*out = *in
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(StorageSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleStorage.
func (in *ConsoleStorage) DeepCopy() *ConsoleStorage {
	if in == nil {
		return nil
	}
	out := new(ConsoleStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Enrollment) DeepCopyInto(out *Enrollment) {
	*out = *in
	if in.CATLS != nil {
		in, out := &in.CATLS, &out.CATLS
		*out = new(CATLS)
		**out = **in
	}
	if in.AdminCerts != nil {
		in, out := &in.AdminCerts, &out.AdminCerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CSR != nil {
		in, out := &in.CSR, &out.CSR
		*out = new(CSR)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Enrollment.
func (in *Enrollment) DeepCopy() *Enrollment {
	if in == nil {
		return nil
	}
	out := new(Enrollment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnrollmentSpec) DeepCopyInto(out *EnrollmentSpec) {
	*out = *in
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(Enrollment)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(Enrollment)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientAuth != nil {
		in, out := &in.ClientAuth, &out.ClientAuth
		*out = new(Enrollment)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnrollmentSpec.
func (in *EnrollmentSpec) DeepCopy() *EnrollmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnrollmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPCA) DeepCopyInto(out *IBPCA) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPCA.
func (in *IBPCA) DeepCopy() *IBPCA {
	if in == nil {
		return nil
	}
	out := new(IBPCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPCA) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPCAList) DeepCopyInto(out *IBPCAList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBPCA, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPCAList.
func (in *IBPCAList) DeepCopy() *IBPCAList {
	if in == nil {
		return nil
	}
	out := new(IBPCAList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPCAList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPCASpec) DeepCopyInto(out *IBPCASpec) {
	*out = *in
	out.License = in.License
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(CAImages)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(CAResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(CAStorages)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigOverride != nil {
		in, out := &in.ConfigOverride, &out.ConfigOverride
		*out = new(ConfigOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.HSM != nil {
		in, out := &in.HSM, &out.HSM
		*out = new(HSM)
		**out = **in
	}
	out.CustomNames = in.CustomNames
	out.Ingress = in.Ingress
	if in.Arch != nil {
		in, out := &in.Arch, &out.Arch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Action = in.Action
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPCASpec.
func (in *IBPCASpec) DeepCopy() *IBPCASpec {
	if in == nil {
		return nil
	}
	out := new(IBPCASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPCAStatus) DeepCopyInto(out *IBPCAStatus) {
	*out = *in
	out.CRStatus = in.CRStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPCAStatus.
func (in *IBPCAStatus) DeepCopy() *IBPCAStatus {
	if in == nil {
		return nil
	}
	out := new(IBPCAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPConsole) DeepCopyInto(out *IBPConsole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPConsole.
func (in *IBPConsole) DeepCopy() *IBPConsole {
	if in == nil {
		return nil
	}
	out := new(IBPConsole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPConsole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPConsoleList) DeepCopyInto(out *IBPConsoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBPConsole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPConsoleList.
func (in *IBPConsoleList) DeepCopy() *IBPConsoleList {
	if in == nil {
		return nil
	}
	out := new(IBPConsoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPConsoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPConsoleSpec) DeepCopyInto(out *IBPConsoleSpec) {
	*out = *in
	out.License = in.License
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(ConsoleImages)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ConsoleResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(ConsoleStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkInfo != nil {
		in, out := &in.NetworkInfo, &out.NetworkInfo
		*out = new(NetworkInfo)
		**out = **in
	}
	out.Ingress = in.Ingress
	if in.ClusterData != nil {
		in, out := &in.ClusterData, &out.ClusterData
		*out = new(consolev1.IBPConsoleClusterData)
		(*in).DeepCopyInto(*out)
	}
	if in.FeatureFlags != nil {
		in, out := &in.FeatureFlags, &out.FeatureFlags
		*out = new(consolev1.FeatureFlags)
		(*in).DeepCopyInto(*out)
	}
	if in.IBMID != nil {
		in, out := &in.IBMID, &out.IBMID
		*out = new(consolev1.IBMID)
		**out = **in
	}
	if in.Proxying != nil {
		in, out := &in.Proxying, &out.Proxying
		*out = new(bool)
		**out = **in
	}
	if in.CRN != nil {
		in, out := &in.CRN, &out.CRN
		*out = new(CRN)
		**out = **in
	}
	if in.Kubeconfig != nil {
		in, out := &in.Kubeconfig, &out.Kubeconfig
		*out = new([]byte)
		if **in != nil {
			in, out := *in, *out
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = new(Versions)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployer != nil {
		in, out := &in.Deployer, &out.Deployer
		*out = new(Deployer)
		**out = **in
	}
	if in.Arch != nil {
		in, out := &in.Arch, &out.Arch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigOverride != nil {
		in, out := &in.ConfigOverride, &out.ConfigOverride
		*out = new(ConsoleOverrides)
		(*in).DeepCopyInto(*out)
	}
	out.Action = in.Action
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPConsoleSpec.
func (in *IBPConsoleSpec) DeepCopy() *IBPConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(IBPConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPConsoleStatus) DeepCopyInto(out *IBPConsoleStatus) {
	*out = *in
	out.CRStatus = in.CRStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPConsoleStatus.
func (in *IBPConsoleStatus) DeepCopy() *IBPConsoleStatus {
	if in == nil {
		return nil
	}
	out := new(IBPConsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPOrderer) DeepCopyInto(out *IBPOrderer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPOrderer.
func (in *IBPOrderer) DeepCopy() *IBPOrderer {
	if in == nil {
		return nil
	}
	out := new(IBPOrderer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPOrderer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPOrdererList) DeepCopyInto(out *IBPOrdererList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBPOrderer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPOrdererList.
func (in *IBPOrdererList) DeepCopy() *IBPOrdererList {
	if in == nil {
		return nil
	}
	out := new(IBPOrdererList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPOrdererList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPOrdererSpec) DeepCopyInto(out *IBPOrdererSpec) {
	*out = *in
	out.License = in.License
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(OrdererImages)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(OrdererResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(OrdererStorages)
		(*in).DeepCopyInto(*out)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigOverride != nil {
		in, out := &in.ConfigOverride, &out.ConfigOverride
		*out = new(json.RawMessage)
		if **in != nil {
			in, out := *in, *out
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
	}
	if in.HSM != nil {
		in, out := &in.HSM, &out.HSM
		*out = new(HSM)
		**out = **in
	}
	if in.IsPrecreate != nil {
		in, out := &in.IsPrecreate, &out.IsPrecreate
		*out = new(bool)
		**out = **in
	}
	if in.ClusterLocation != nil {
		in, out := &in.ClusterLocation, &out.ClusterLocation
		*out = make([]IBPOrdererClusterLocation, len(*in))
		copy(*out, *in)
	}
	if in.ClusterConfigOverride != nil {
		in, out := &in.ClusterConfigOverride, &out.ClusterConfigOverride
		*out = make([]*json.RawMessage, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(json.RawMessage)
				if **in != nil {
					in, out := *in, *out
					*out = make([]byte, len(*in))
					copy(*out, *in)
				}
			}
		}
	}
	if in.ClusterSecret != nil {
		in, out := &in.ClusterSecret, &out.ClusterSecret
		*out = make([]*SecretSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SecretSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NodeNumber != nil {
		in, out := &in.NodeNumber, &out.NodeNumber
		*out = new(int)
		**out = **in
	}
	out.Ingress = in.Ingress
	if in.Arch != nil {
		in, out := &in.Arch, &out.Arch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisableNodeOU != nil {
		in, out := &in.DisableNodeOU, &out.DisableNodeOU
		*out = new(bool)
		**out = **in
	}
	out.CustomNames = in.CustomNames
	out.Action = in.Action
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPOrdererSpec.
func (in *IBPOrdererSpec) DeepCopy() *IBPOrdererSpec {
	if in == nil {
		return nil
	}
	out := new(IBPOrdererSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPOrdererStatus) DeepCopyInto(out *IBPOrdererStatus) {
	*out = *in
	out.CRStatus = in.CRStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPOrdererStatus.
func (in *IBPOrdererStatus) DeepCopy() *IBPOrdererStatus {
	if in == nil {
		return nil
	}
	out := new(IBPOrdererStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPPeer) DeepCopyInto(out *IBPPeer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPPeer.
func (in *IBPPeer) DeepCopy() *IBPPeer {
	if in == nil {
		return nil
	}
	out := new(IBPPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPPeer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPPeerList) DeepCopyInto(out *IBPPeerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBPPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPPeerList.
func (in *IBPPeerList) DeepCopy() *IBPPeerList {
	if in == nil {
		return nil
	}
	out := new(IBPPeerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPPeerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPPeerSpec) DeepCopyInto(out *IBPPeerSpec) {
	*out = *in
	out.License = in.License
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(PeerImages)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(PeerResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(PeerStorages)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigOverride != nil {
		in, out := &in.ConfigOverride, &out.ConfigOverride
		*out = new(json.RawMessage)
		if **in != nil {
			in, out := *in, *out
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
	}
	if in.HSM != nil {
		in, out := &in.HSM, &out.HSM
		*out = new(HSM)
		**out = **in
	}
	if in.DisableNodeOU != nil {
		in, out := &in.DisableNodeOU, &out.DisableNodeOU
		*out = new(bool)
		**out = **in
	}
	out.CustomNames = in.CustomNames
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Ingress = in.Ingress
	if in.Arch != nil {
		in, out := &in.Arch, &out.Arch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DindArgs != nil {
		in, out := &in.DindArgs, &out.DindArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Action = in.Action
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPPeerSpec.
func (in *IBPPeerSpec) DeepCopy() *IBPPeerSpec {
	if in == nil {
		return nil
	}
	out := new(IBPPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPPeerStatus) DeepCopyInto(out *IBPPeerStatus) {
	*out = *in
	out.CRStatus = in.CRStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPPeerStatus.
func (in *IBPPeerStatus) DeepCopy() *IBPPeerStatus {
	if in == nil {
		return nil
	}
	out := new(IBPPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MSP) DeepCopyInto(out *MSP) {
	*out = *in
	if in.CACerts != nil {
		in, out := &in.CACerts, &out.CACerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IntermediateCerts != nil {
		in, out := &in.IntermediateCerts, &out.IntermediateCerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdminCerts != nil {
		in, out := &in.AdminCerts, &out.AdminCerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MSP.
func (in *MSP) DeepCopy() *MSP {
	if in == nil {
		return nil
	}
	out := new(MSP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MSPSpec) DeepCopyInto(out *MSPSpec) {
	*out = *in
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientAuth != nil {
		in, out := &in.ClientAuth, &out.ClientAuth
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MSPSpec.
func (in *MSPSpec) DeepCopy() *MSPSpec {
	if in == nil {
		return nil
	}
	out := new(MSPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererConnectionProfile) DeepCopyInto(out *OrdererConnectionProfile) {
	*out = *in
	out.Endpoints = in.Endpoints
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererConnectionProfile.
func (in *OrdererConnectionProfile) DeepCopy() *OrdererConnectionProfile {
	if in == nil {
		return nil
	}
	out := new(OrdererConnectionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererCustomNames) DeepCopyInto(out *OrdererCustomNames) {
	*out = *in
	out.PVC = in.PVC
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererCustomNames.
func (in *OrdererCustomNames) DeepCopy() *OrdererCustomNames {
	if in == nil {
		return nil
	}
	out := new(OrdererCustomNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererResources) DeepCopyInto(out *OrdererResources) {
	*out = *in
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Orderer != nil {
		in, out := &in.Orderer, &out.Orderer
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPCProxy != nil {
		in, out := &in.GRPCProxy, &out.GRPCProxy
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Enroller != nil {
		in, out := &in.Enroller, &out.Enroller
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.HSMDaemon != nil {
		in, out := &in.HSMDaemon, &out.HSMDaemon
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererResources.
func (in *OrdererResources) DeepCopy() *OrdererResources {
	if in == nil {
		return nil
	}
	out := new(OrdererResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererStorages) DeepCopyInto(out *OrdererStorages) {
	*out = *in
	if in.Orderer != nil {
		in, out := &in.Orderer, &out.Orderer
		*out = new(StorageSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererStorages.
func (in *OrdererStorages) DeepCopy() *OrdererStorages {
	if in == nil {
		return nil
	}
	out := new(OrdererStorages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerConnectionProfile) DeepCopyInto(out *PeerConnectionProfile) {
	*out = *in
	out.Endpoints = in.Endpoints
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerConnectionProfile.
func (in *PeerConnectionProfile) DeepCopy() *PeerConnectionProfile {
	if in == nil {
		return nil
	}
	out := new(PeerConnectionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerCustomNames) DeepCopyInto(out *PeerCustomNames) {
	*out = *in
	out.PVC = in.PVC
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerCustomNames.
func (in *PeerCustomNames) DeepCopy() *PeerCustomNames {
	if in == nil {
		return nil
	}
	out := new(PeerCustomNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerResources) DeepCopyInto(out *PeerResources) {
	*out = *in
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPCProxy != nil {
		in, out := &in.GRPCProxy, &out.GRPCProxy
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.FluentD != nil {
		in, out := &in.FluentD, &out.FluentD
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.DinD != nil {
		in, out := &in.DinD, &out.DinD
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CouchDB != nil {
		in, out := &in.CouchDB, &out.CouchDB
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CCLauncher != nil {
		in, out := &in.CCLauncher, &out.CCLauncher
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Enroller != nil {
		in, out := &in.Enroller, &out.Enroller
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.HSMDaemon != nil {
		in, out := &in.HSMDaemon, &out.HSMDaemon
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerResources.
func (in *PeerResources) DeepCopy() *PeerResources {
	if in == nil {
		return nil
	}
	out := new(PeerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerStorages) DeepCopyInto(out *PeerStorages) {
	*out = *in
	if in.StateDB != nil {
		in, out := &in.StateDB, &out.StateDB
		*out = new(StorageSpec)
		**out = **in
	}
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(StorageSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerStorages.
func (in *PeerStorages) DeepCopy() *PeerStorages {
	if in == nil {
		return nil
	}
	out := new(PeerStorages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSpec) DeepCopyInto(out *SecretSpec) {
	*out = *in
	if in.Enrollment != nil {
		in, out := &in.Enrollment, &out.Enrollment
		*out = new(EnrollmentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MSP != nil {
		in, out := &in.MSP, &out.MSP
		*out = new(MSPSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSpec.
func (in *SecretSpec) DeepCopy() *SecretSpec {
	if in == nil {
		return nil
	}
	out := new(SecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Versions) DeepCopyInto(out *Versions) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = make(map[string]VersionCA, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = make(map[string]VersionPeer, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Orderer != nil {
		in, out := &in.Orderer, &out.Orderer
		*out = make(map[string]VersionOrderer, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Versions.
func (in *Versions) DeepCopy() *Versions {
	if in == nil {
		return nil
	}
	out := new(Versions)
	in.DeepCopyInto(out)
	return out
}
