name: Build Operator image

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build
        run: |
          scripts/install-tools.sh
          make image
